package com.door43.translationstudio.dialogs;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.door43.translationstudio.MainApplication;
import com.door43.translationstudio.R;
import com.door43.translationstudio.SettingsActivity;
import com.door43.translationstudio.projects.Model;
import com.door43.translationstudio.tasks.LoadModelFontTask;
import com.door43.translationstudio.util.AnimationUtilities;
import com.door43.translationstudio.util.AppContext;
import com.door43.util.tasks.ManagedTask;
import com.door43.util.tasks.TaskManager;
import com.door43.util.tasks.ThreadableUI;
import com.nostra13.universalimageloader.core.listener.SimpleImageLoadingListener;

/**
 * Created by joel on 8/29/2014.
 */
public class ModelItemAdapter extends BaseAdapter {

    private final MainApplication mContext;
    private final float mImageWidth;
    private final boolean mIndicateSelected;
    private final boolean mIndicateStatus;
    private final String mGroupTaskId;
    private final int mDefaultIconResource;
    private final int mDefaultIconSelectedResource;
    private Model[] mModels;

    /**
     *
     * @param c
     * @param models
     * @param defaultIconResource
     * @param groupTaskId  an id to add to tasks use in rendering the items. This allows you to safely cancel all tasks generated by this adapter.
     */
    public ModelItemAdapter(MainApplication c, Model[] models, int defaultIconResource, int defaultIconSelectedResource, String groupTaskId) {
        mContext = c;
        mModels = models;
        mImageWidth = mContext.getResources().getDimension(R.dimen.model_list_item_image_width);
        mIndicateSelected = true;
        mIndicateStatus = true;
        mGroupTaskId = groupTaskId;
        mDefaultIconResource = defaultIconResource;
        mDefaultIconSelectedResource = defaultIconSelectedResource;
    }

    /**
     *
     * @param c
     * @param models
     * @param indicatSelection highlight selected project
     */
    public ModelItemAdapter(MainApplication c, Model[] models, boolean indicatSelection, int defaultIconResource, int defaultIconSelectedResource, String groupTaskId) {
        mContext = c;
        mModels = models;
        mImageWidth = mContext.getResources().getDimension(R.dimen.model_list_item_image_width);
        mIndicateSelected = indicatSelection;
        mIndicateStatus = true;
        mGroupTaskId = groupTaskId;
        mDefaultIconResource = defaultIconResource;
        mDefaultIconSelectedResource = defaultIconSelectedResource;
    }

    /**
     *
     * @param c
     * @param models
     * @param indicatSelection highlight selected project
     * @param indicateStatus display project status
     */
    public ModelItemAdapter(MainApplication c, Model[] models, boolean indicatSelection, boolean indicateStatus, int defaultIconResource, int defaultIconSelectedResource, String groupTaskId) {
        mContext = c;
        mModels = models;
        mImageWidth = mContext.getResources().getDimension(R.dimen.model_list_item_image_width);
        mIndicateSelected = indicatSelection;
        mIndicateStatus = indicateStatus;
        mGroupTaskId = groupTaskId;
        mDefaultIconResource = defaultIconResource;
        mDefaultIconSelectedResource = defaultIconSelectedResource;
    }

    @Override
    public int getCount() {
        return mModels.length;
    }

    @Override
    public Model getItem(int i) {
        return mModels[i];
    }

    @Override
    public long getItemId(int i) {
        return 0;
    }

    @Override
    public View getView(final int position, View convertView, final ViewGroup parent) {
        View v = convertView;
        ViewHolder holder = new ViewHolder();
        final String imageUri;

        if(AppContext.assetExists(getItem(position).getImagePath())) {
            imageUri = "assets://"+ getItem(position).getImagePath();
        } else if(AppContext.assetExists(getItem(position).getDefaultImagePath())){
            imageUri = "assets://"+ getItem(position).getDefaultImagePath();
        } else {
            imageUri = null;
        }

        if (convertView == null) {
            LayoutInflater inflater = (LayoutInflater) mContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            v = inflater.inflate(R.layout.fragment_model_list_item, null);
            // layout
            holder.bodyLayout = (RelativeLayout)v.findViewById(R.id.bodyLayout);
            holder.image = (ImageView)v.findViewById(R.id.modelImage);
            holder.title = (TextView)v.findViewById(R.id.modelTitle);
            holder.description = (TextView)v.findViewById(R.id.modelDescription);

            // icons
//            holder.audioIcon = (ImageView)v.findViewById(R.id.audioIcon);
            holder.languagesIcon = (ImageView)v.findViewById(R.id.languagesIcon);
            holder.translationIcon = (ImageView)v.findViewById(R.id.translationIcon);
            holder.translationNotesIcon = (ImageView)v.findViewById(R.id.translationNotesIcon);
            holder.iconGroup = (LinearLayout)v.findViewById(R.id.iconGroupLayout);
            v.setTag(holder);
        } else {
            holder = (ViewHolder)v.getTag();
        }

        holder.image.clearAnimation();
        holder.bodyLayout.clearAnimation();

        // set title and description
        holder.title.setText(getItem(position).getTitle());
        holder.description.setText(getItem(position).getDescription());
        if(getItem(position).getDescription() == null || getItem(position).getDescription().equals("")) {
            holder.description.setVisibility(View.GONE);
        } else {
            holder.description.setVisibility(View.VISIBLE);
        }

        // highlight selected item
        boolean isSelected = false;
        if(getItem(position).isSelected() && mIndicateSelected) {
            isSelected = true;
            v.setBackgroundColor(mContext.getResources().getColor(R.color.accent));
            holder.title.setTextColor(mContext.getResources().getColor(R.color.light_primary_text));
            holder.description.setTextColor(mContext.getResources().getColor(R.color.light_secondary_text));
        } else {
            v.setBackgroundColor(Color.TRANSPARENT);
            holder.title.setTextColor(mContext.getResources().getColor(R.color.dark_primary_text));
            holder.description.setTextColor(mContext.getResources().getColor(R.color.dark_secondary_text));
        }

        final ViewHolder staticHolder = holder;
        final Model staticModel = getItem(position);
        final boolean staticIsSelected = isSelected;

        // set fontface
        String selectedFontName = AppContext.context().getUserPreferences().getString(SettingsActivity.KEY_PREF_TRANSLATION_TYPEFACE, AppContext.context().getResources().getString(R.string.pref_default_translation_typeface));
        if(!holder.hasFont || !holder.fontName.equals(selectedFontName)) {
            if (holder.fontTaskId != null) {
                LoadModelFontTask oldTask = (LoadModelFontTask) TaskManager.getTask(holder.fontTaskId);
                if (oldTask != null) {
                    TaskManager.cancelTask(oldTask);
                    TaskManager.clearTask(oldTask);
                }
                holder.fontTaskId = null;
            }
            LoadModelFontTask task = new LoadModelFontTask(getItem(position), mIndicateSelected);
            task.addOnFinishedListener(new ManagedTask.OnFinishedListener() {
                @Override
                public void onFinished(final ManagedTask task) {
                    TaskManager.clearTask(task);
                    if (!task.isCanceled()) {
                        Handler hand = new Handler(Looper.getMainLooper());
                        hand.post(new Runnable() {
                            @Override
                            public void run() {
                                staticHolder.hasFont = true;
                                staticHolder.fontName = ((LoadModelFontTask) task).getTypefaceName();
                                staticHolder.title.setTypeface(((LoadModelFontTask) task).getTypeface(), 0);
                                staticHolder.description.setTypeface(((LoadModelFontTask) task).getTypeface(), 0);
                            }
                        });
                    }
                }
            });
            TaskManager.addTask(task);
            if (mGroupTaskId != null) {
                TaskManager.groupTask(task, mGroupTaskId);
            }
            holder.fontTaskId = task.getTaskId();
        }

        // set font size
        float fontsize = AppContext.typefaceSize();
        holder.title.setTextSize(fontsize);
        holder.description.setTextSize((float) (fontsize * 0.7));

        // icons
//        holder.translationNotesIcon.setBackgroundResource(R.drawable.ic_project_status_blank);
//        holder.translationIcon.setBackgroundResource(R.drawable.ic_project_status_blank);
//        holder.languagesIcon.setBackgroundResource(R.drawable.ic_project_status_blank);
//        holder.audioIcon.setBackgroundResource(R.drawable.ic_project_status_blank);
        holder.iconGroup.setVisibility(View.INVISIBLE);

        // load image
        if(imageUri == null) {
            holder.image.setVisibility(View.VISIBLE);
            if(isSelected) {
                if(mDefaultIconSelectedResource > 0) {
                    holder.image.setImageResource(mDefaultIconSelectedResource);
                } else {
                    holder.image.setVisibility(View.GONE);
                }
            } else {
                if(mDefaultIconResource > 0) {
                    holder.image.setImageResource(mDefaultIconResource);
                } else {
                    holder.image.setVisibility(View.GONE);
                }
            }
        } else {
            holder.image.setVisibility(View.GONE);
            mContext.getImageLoader().loadImage(imageUri, new SimpleImageLoadingListener() {
                @Override
                public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                    // load values
                    staticHolder.image.setImageBitmap(loadedImage);
                    staticHolder.image.setVisibility(View.VISIBLE);

                    // animate views
                    AnimationUtilities.fadeIn(staticHolder.image, 100);
                }
            });
        }

        // enable icons
        if(holder.statusThread != null) {
            holder.statusThread.stop();
        }
        holder.statusThread = new ThreadableUI(mContext) {
            public boolean isTranslatingNotes;
            private boolean isTranslating;
            private boolean isTranslatingGlobal;
            private boolean hasAudio;

            @Override
            public void onStop() {

            }

            @Override
            public void run() {
                isTranslating = staticModel.isTranslating();
                isTranslatingNotes = staticModel.isTranslatingNotes();
                isTranslatingGlobal = staticModel.isTranslatingGlobal() || staticModel.isTranslatingNotesGlobal();
                hasAudio = false;
            }

            @Override
            public void onPostExecute() {
                if(staticIsSelected) {
                    if(isTranslating) staticHolder.translationIcon.setBackgroundResource(R.drawable.icon_edit_white);
//                    if(isTranslatingGlobal) staticHolder.languagesIcon.setBackgroundResource(R.drawable.ic_project_status_global);
//                    if(hasAudio) staticHolder.audioIcon.setBackgroundResource(R.drawable.ic_project_status_audio);
//                    if(isTranslatingNotes) staticHolder.translationNotesIcon.setBackgroundResource(R.drawable.ic_project_status_translating_notes);
//                } else {
//                    if(isTranslating) staticHolder.translationIcon.setBackgroundResource(R.drawable.icon_edit_blue);
//                    if(isTranslatingGlobal) staticHolder.languagesIcon.setBackgroundResource(R.drawable.ic_project_status_global_light);
//                    if(hasAudio) staticHolder.audioIcon.setBackgroundResource(R.drawable.ic_project_status_audio_light);
//                    if(isTranslatingNotes) staticHolder.translationNotesIcon.setBackgroundResource(R.drawable.ic_project_status_translating_notes_light);
                }
                if(isTranslating || isTranslatingGlobal || hasAudio || isTranslatingNotes) {
                    staticHolder.iconGroup.setVisibility(View.VISIBLE);
                    AnimationUtilities.fadeIn(staticHolder.iconGroup, 100);
                } else {
                    staticHolder.iconGroup.setVisibility(View.INVISIBLE);
                }
            }
        };
        if(mIndicateStatus) {
            holder.statusThread.start();
        }

        return v;
    }

    /**
     * Changes the dataset
     * @param models
     */
    public void changeDataSet(Model[] models) {
        mModels = models;
        notifyDataSetChanged();
    }

    /**
     * Improves performance
     */
    private static class ViewHolder {
        public ImageView image;
        public RelativeLayout bodyLayout;
        public TextView title;
        public TextView description;

        public ImageView translationIcon;
        public ImageView languagesIcon;
        public ImageView audioIcon;
        public LinearLayout iconGroup;

        public ThreadableUI statusThread;
        public Object fontTaskId;
        public boolean hasFont;
        public ImageView translationNotesIcon;
        public String fontName;
    }
}
